//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLog
    {
        public int Id { get; set; }
        public bool Accomplished { get; set; }
        public string Memo { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual ProfileActivity ProfileActivityKey { get; set; }
        public virtual Subscription SubscriptionKey { get; set; }
    }
}
