//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRelationship
    {
        public CustomerRelationship()
        {
            this.Contracts = new HashSet<Contract>();
        }
    
        public bool SelfCoached { get; set; }
        public System.Guid ClientKey { get; set; }
        public System.Guid CoachKey { get; set; }
    
        public virtual User UserClientKey { get; set; }
        public virtual User UserCoachKey { get; set; }
        public virtual ICollection<Contract> Contracts { get; set; }
    }
}
