//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iWorkoutEDMContainer : DbContext
    {
        public iWorkoutEDMContainer()
            : base("name=iWorkoutEDMContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<CustomerRelationship> CustomerRelationships { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<ProgramProfile> ProgramProfiles { get; set; }
        public virtual DbSet<ProfileDetail> ProfileDetails { get; set; }
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<ActivityType> ActivityTypes { get; set; }
        public virtual DbSet<ActivityLog> ActivityLogs { get; set; }
        public virtual DbSet<ProfileActivity> ProfileActivities { get; set; }
        public virtual DbSet<Subscription> Subscriptions { get; set; }
    }
}
