//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileDetail
    {
        public ProfileDetail()
        {
            this.CycleLength = 1;
            this.CycleRepeatCount = 1;
            this.ProgramProfiles = new HashSet<ProgramProfile>();
            this.ProfileActivities = new HashSet<ProfileActivity>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Priority { get; set; }
        public int CycleLength { get; set; }
        public int CycleRepeatCount { get; set; }
    
        public virtual ICollection<ProgramProfile> ProgramProfiles { get; set; }
        public virtual ICollection<ProfileActivity> ProfileActivities { get; set; }
        public virtual User UserOwnerKey { get; set; }
    }
}
