//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileActivity
    {
        public ProfileActivity()
        {
            this.ActivityLogs = new HashSet<ActivityLog>();
        }
    
        public int Id { get; set; }
        public int Priority { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Activity ActivityKey { get; set; }
        public virtual ProfileDetail ProfileDetailKey { get; set; }
        public virtual ICollection<ActivityLog> ActivityLogs { get; set; }
    }
}
