//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public Subscription()
        {
            this.ActivityLogs = new HashSet<ActivityLog>();
        }
    
        public int Id { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime StartDate { get; set; }
    
        public virtual Program ProgramKey { get; set; }
        public virtual User UserClientKey { get; set; }
        public virtual ICollection<ActivityLog> ActivityLogs { get; set; }
    }
}
