//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.CustomerRelationships = new HashSet<CustomerRelationship>();
            this.CustomerRelationships1 = new HashSet<CustomerRelationship>();
            this.Programs = new HashSet<Program>();
            this.Subscriptions = new HashSet<Subscription>();
            this.ProfileDetails = new HashSet<ProfileDetail>();
            this.Activities = new HashSet<Activity>();
        }
    
        public System.Guid Id { get; set; }
        public string Handle { get; set; }
    
        public virtual UserType UserTypeKey { get; set; }
        public virtual ICollection<CustomerRelationship> CustomerRelationships { get; set; }
        public virtual ICollection<CustomerRelationship> CustomerRelationships1 { get; set; }
        public virtual ICollection<Program> Programs { get; set; }
        public virtual ICollection<Subscription> Subscriptions { get; set; }
        public virtual ICollection<ProfileDetail> ProfileDetails { get; set; }
        public virtual ICollection<Activity> Activities { get; set; }
    }
}
